//home page
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_LANDING_PAGE_BLOGS_SUCCESS = 'GET_LANDING_PAGE_BLOGS_SUCCESS';

//Auth
export const REGISTER_API_ERROR = 'REGISTER_API_ERROR';
export const LOGIN_API_ERROR = 'LOGIN_API_ERROR';
export const AUTHENTICATING_USER = 'AUTHENTICATING_USER';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL';
export const TOGGLE_AUTH_MODAL = 'TOGGLE_AUTH_MODAL';